study_name: dev
experiment_name: dev
seed: 42
split_name: S29-0
# split_name: dev

allow_overwrite_trial: true  # whether to allow overwrites in the artifacts/ dir
allow_diff_study: true
allow_diff_experiment: true

# (experiment)
model_type: bioclip
loss_type: infonce

# (experiment -- except for checkpoint_every)
n_epochs: 1000
checkpoint_every: 2
lr_init: 1.0e-5
lr_decay: 0.99
batch_size_train: 1024
batch_size_val: 2048

# (experiment)
freeze_text_encoder: false
freeze_image_encoder: false

# (experiment -- except for verbose_batch_loss)
cached_imgs: null  # options: null / pl / pp
mp_train: true  # whether to use mixed precision for training
drop_partial_batch_train: true
verbose_batch_loss: false

# (experiment)
text_preps_type_train: mixed
text_preps_type_val: bioclip_sci
