study_name:      dev
experiment_name: dev
seed:            42
split_name:      S29-0
# split_name:      D2
# split_name:      dev

verbose_batch_loss: true

allow_overwrite_trial: true  # whether to allow overwrites in the artifacts/study/experiment/trial/ dir
allow_diff_study:      true
allow_diff_experiment: true

model_type: bioclip
loss_type:  infonce
class_weighting:
  type:    inv_freq  # options: null / inv_freq / class_balanced
  if_gamma: 0.5  # (0.0, 1.0]; "inverse-frequency gamma", only used for type: inv_freq; 1 / n_c^(if_gamma); if_gamma = 1.0 --> 1 / n_c (classic scheme), if_gamma = 0.5 --> 1 / sqrt(n_c), if_gamma = 0.0 --> no weighting (uniform)
  cb_beta:  0.9999  # [0.0, 1.0); only used for type: class_balanced; controls aggressiveness
focal:
  enabled:   true
  gamma:     2.0  # [0, inf); down-weights easy samples, larger gamma --> stronger focus on hard cases; 1-2 for softmax (InfoNCE), 2 for sigmoid; FL reduces to CE when gamma = 0
  alpha_pos: 0.25  # how much weight positives get relative to negatives inside the focal loss term e.g. alpha_t = alpha_pos for positives, alpha_t = (1 - alpha_pos) for negatives

n_epochs:         1000
checkpoint_every: 1
# batch_size_train: 32
# batch_size_train: 512
batch_size_train: 1024
# batch_size_train: 2048
# batch_size_train: 4096
# batch_size_train: 8192
# batch_size_train: 16384
# batch_size_train: 32768
batch_size_val:   1024

drop_partial_batch_train: true

lr_init:      1.0e-5
weight_decay: 0.0  # CLIP paper recommends weight_decay = 0.2
beta1:        0.9  # CLIP paper recommends Beta1 = 0.9
beta2:        0.98  # CLIP paper recommends Beta2 = 0.999 (ResNet) / 0.98 (ViT)
eps:          1.0e-6  # CLIP paper recommends eps = 1.0e-8 (ResNet) / 1.0e-6 (ViT)

lr_sched:
  # Exponential LR Scheduler
  type: exp
  args:
    lr_min: 1.0e-9
  args_sched:
    gamma: 0.985
  # # Plateau LR Scheduler
  # type: plat  # may also want to tweak threshold / eps
  # args:
  #   reset_best_val: true  # (true) reset best validation score after LR drop to avoid early plateauing
  #   val_type:       loss  # options: loss / perf
  # args_sched:
  #   factor:   0.61803398875  # golden ratio
  #   patience: 1
  #   cooldown: 1
  #   min_lr:   1.0e-7
  # # Cosine LR Scheduler
  # type: cos
  # args:
  #   dummy: null
  # args_sched:
  #   T_max:   5  # half-period
  #   eta_min: 1.0e-7
  # # Cosine Warm-Restarts LR Scheduler
  # type: coswr
  # args:
  #   dummy: null
  # args_sched:
  #   T_0:     7  # period
  #   eta_min: 1.0e-7
  # # Cosine X Exponential LR Scheduler
  # type: cosXexp
  # args:
  #   gamma:      0.98
  #   period:     10
  #   peak_ratio: 10
  #   lr_nom_min: 5.0e-7
  # Cosine Warm-Restarts X Exponential LR Scheduler
  # type: coswrXexp
  # args:
  #   gamma:      0.98
  #   period:     10
  #   peak_ratio: 10
  #   lr_nom_min: 5.0e-7

freeze_text_encoder:  false
freeze_image_encoder: false

cached_imgs: null  # options: null / pl / pp
mixed_prec:  true  # mixed precision for training and validation
act_chkpt:   false  # activation checkpointing

text_preps_type_train: mixed
text_preps_type_val:   bioclip_sci
