campaign_name: dev
setting_name: dev_dataset
seed: 42
dataset: nymph  # {bryo, cub, lepid, nymph}
split_name: D10

sample_volume: 1_000_000
eval_every: 50_000
chkpt_every: 1
batch_size: 1024  # {16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768}
dv_batching: false  # (true) dorsal/ventral-homogeneous batching

dev:
  allow_overwrite_trial: true
  allow_diff_campaign: true
  allow_diff_setting: true
  view_imgs: 100  # if set > 0, will save the first <view_imgs> number of images during training (post-augmentation) to a directory: <campaign_name>/<setting_name>/<dataset>/<seed>/train_imgs/
  debug_mode: false

arch:  # architecture
  model_type: siglip_vitb16  # commonly used: {bioclip, clip_vitb16, siglip_vitb16}
  non_causal: false  # (true) converts text encoder causal attention mask to non-causal (zeros on diagonal + lower triangle, -inf on upper --> all zeros) -- only applicable to CLIP (SigLIP already uses non-causal i.e. bidirectional)

img_norm: dataset  # {default, dataset}

loss:
  type: bce  # {infonce1, infonce2, bce}
  sim: cos  # {cos, geo1, geo2}
  targ: multipos  # {aligned, multipos, tax, phylo}
  wting: true
  focal: true
  dyn_smr: true  # dynamic similarity mass rebalancing (multi-pos, aligned, hierarchical?); only relevant for BCE

# same settings should be equivalent
loss2:  # secondary loss
  mix: 0.0  # set to 0.0 to disable computation
  type: bce  # {infonce1, infonce2, bce}
  sim: cos  # {cos, geo1, geo2}
  targ: phylo
  wting: true
  focal: true
  dyn_smr: true  # dynamic similarity mass rebalancing (multi-pos, aligned, hierarchical?); only relevant for BCE

opt:  # optimization
  lr:  # learning rate
    init: 1.0e-5
    sched: cos
    warmup: 100_000  # sample volume for linear LR warmup
  l2reg: null  # if `null`, resolved from model-specific default hyperparam config
  beta1: 0.9  # CLIP paper recommends Beta1 = 0.9
  beta2: null  # if `null`, resolved from model-specific default hyperparam config
  eps: 1.0e-6  # CLIP paper recommends eps = 1.0e-6 (ViT)

freeze:
  image: false
  text: false

text_template:
  train: train
  valid: bioclip_sci

logging: true
metrics_plot_every_batches: 100