n_trials: 3
# datasets: [bryo, cub, lepid, nymph]
datasets: [cub, nymph]

baseline_overrides:
  - - {loss2.mix: 0.3, loss2.targ: phylo, name: hp}
    - {loss.targ: multipos, name: sw}
  - - {batch_size: 2_048, name: 2k}
    - {batch_size: 1_024, name: 1k}
  - - {opt.lr.init: 1.2e-5, name: LR-init-1.2e-5}
    - {opt.lr.init: 7.0e-6, name: LR-init-7.0e-6}

suffix: null  # {null, [str]}; no suffix if set to null
