n_trials: 3
datasets: [cub, nymph]

baseline: false  # {true, false}; (true) also run train.yaml config as-is as "baseline" setting
baseline_overrides:
  - - {loss2.mix: 0.3, loss2.targ: phylo, batch_size: [1_024, 2_048], opt.lr.init: [7.0e-6, 1.2e-5], name: hp}
    - {loss.targ: sw, batch_size: [1_024, 2_048], opt.lr.init: [7.0e-6, 1.2e-5], name: sw}
  - - {loss.wting.type: inv_freq}
    - {loss.wting.type: class_bal}

suffix: null  # {null, [str]}; no suffix if set to null
