n_trials: 1
datasets: [cub]

ablation_arms:
  - - {loss.targ: mp}
    - {loss.targ: sp}
  - - {loss.sim: cos}
    - {loss.sim: geo1}

hpo_coords:
  - - {opt.lr.init: [2.0e-6, 2.0e-5, 2.0e-4]}
  - - {loss.logits.temp.init: [0.0, 0.1, 0.2]}

suffix: null  # {null, [str]}; no suffix if set to null
