# Adam: LR-init ∝ sqrt(B)

n_trials: 3
datasets: [nymph, lepid]

baseline: false  # {true, false}; (true) also run train.yaml config as-is as "baseline" setting
baseline_overrides:
  - - {batch_size: 1_024, opt.lr.init: 2.0e-5, name: bs1k}
    - {batch_size: 2_048, opt.lr.init: 2.828e-5, name: bs2k}
    - {batch_size: 4_096, opt.lr.init: 4.0e-5, name: bs4k}
    - {batch_size: 8_192, opt.lr.init: 5.657e-5, name: bs8k}
    - {batch_size: 16_384, opt.lr.init: 8.0e-5, name: bs16k}
    - {batch_size: 32_768, opt.lr.init: 1.131e-4, name: bs32k}
  - - {loss2.mix: 0.3, loss2.targ: phylo, name: hp}
    - {loss.targ: sw, name: sw}
    - {loss.targ: iw, name: iw}
  - - {n_epochs: 140, name: 140ep}
    - {n_epochs: 70, name: 70ep}

suffix: null  # {null, [str]}; no suffix if set to null
