rdpath_model: null  # relative dirpath to checkpoint directory (contains model.pt; set null for base model)
# rdpath_model: artifacts/devdev/settings/hp/nymph/42/chkpts/final  # dataset, split, model_type, img_norm are overridden if rdpath_model is specified
dataset: nymph  # {bryo, cub, lepid, nymph}
split: D10  # {D10, dev}
eval_type: val  # {val, test}

batch_size: 1_024  # 32, 64, 128, 256, 512, 1_024, 2_048, 4_096, 8_192, 16_384, 32_768

arch:  # architecture
  model_type: siglip_vitb16  # {bioclip, clip_vitb16, siglip_vitb16}

img_norm: default  # {default, dataset}

text_template: sci  # following BioCLIP eval protocol