seed:       42
split_name: S29-42
# split_name: dev

allow_overwrite: false  # <-- guess this doesn't matter now (verify)

pct_eval:    0.29
pct_ood_tol: 0.0001  # tolerance for how close OOD sample volume must be to target percentage; careful, this parameter dictates required accuracy as the stopping criterion for a random search, too low is no no (0.0001 is good)

nst_names: ["1-19", "20-99", "100-499", "500+"]
nst_seps:  [19, 99, 499]  # divides n-shot space into len(nst_seps)+1 buckets, last bucket is if n is greater than the last separation
# nst_names: ["1", "2", "3", "4", "5", "6-10", "11-20", "21-50", "51-100", "101+"]
# nst_seps:  [1, 2, 3, 4, 5, 10, 20, 50, 100]